import {
  existsSync,
  mkdirSync,
  readFileSync,
  writeFileSync,
  copyFileSync,
} from "node:fs";
import { randomBytes } from "node:crypto";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { spawnSync } from "node:child_process";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");

function log(msg) {
  console.log(`  ${msg}`);
}

function parseEnv(text) {
  const out = {};
  for (const line of text.split(/\r?\n/)) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const eq = trimmed.indexOf("=");
    if (eq === -1) continue;
    const key = trimmed.slice(0, eq).trim();
    let value = trimmed.slice(eq + 1).trim();
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }
    out[key] = value;
  }
  return out;
}

function stringifyEnv(vars, headerLines = []) {
  const lines = [...headerLines];
  for (const [key, value] of Object.entries(vars)) {
    if (value === undefined) continue;
    lines.push(`${key}=${value}`);
  }
  return `${lines.join("\n")}\n`;
}

function ensureCopy(srcRel, destRel) {
  const src = join(root, srcRel);
  const dest = join(root, destRel);
  if (!existsSync(src)) {
    log(`skip ${destRel} (missing template ${srcRel})`);
    return;
  }
  if (existsSync(dest)) {
    log(`keep ${destRel} (already exists)`);
    return;
  }
  mkdirSync(dirname(dest), { recursive: true });
  copyFileSync(src, dest);
  log(`create ${destRel}`);
}

function isPlaceholderDb(value) {
  if (!value) return true;
  return (
    value.includes("user:pass@localhost") ||
    value.includes("postgres://user:pass")
  );
}

console.log("\nBaseer Portfolio setup\n");

ensureCopy(".env.example", ".env");
ensureCopy("apps/web/.dev.vars.example", "apps/web/.dev.vars");
ensureCopy("apps/web/.env.example", "apps/web/.env");

const envPath = join(root, ".env");
const devVarsPath = join(root, "apps/web/.dev.vars");
const env = existsSync(envPath) ? parseEnv(readFileSync(envPath, "utf8")) : {};
const devVars = existsSync(devVarsPath)
  ? parseEnv(readFileSync(devVarsPath, "utf8"))
  : {};

const databaseUrl =
  (!isPlaceholderDb(env.DATABASE_URL) && env.DATABASE_URL) ||
  (!isPlaceholderDb(devVars.DATABASE_URL) && devVars.DATABASE_URL) ||
  env.DATABASE_URL ||
  devVars.DATABASE_URL ||
  "postgres://user:pass@localhost:5432/baseer_portfolio";

const ownerId = env.OWNER_ID || devVars.OWNER_ID || "seed-user-baseer";
const authSecret =
  env.BETTER_AUTH_SECRET ||
  devVars.BETTER_AUTH_SECRET ||
  randomBytes(32).toString("hex");
const adminPassword =
  env.ADMIN_PASSWORD ||
  devVars.ADMIN_PASSWORD ||
  "changeme-baseer-admin";

env.DATABASE_URL = databaseUrl;
env.OWNER_ID = ownerId;
env.APP_URL = env.APP_URL || "http://localhost:5173";
env.ADMIN_EMAIL = env.ADMIN_EMAIL || "baseer@baseer.co.uk";
env.ADMIN_NAME = env.ADMIN_NAME || "Baseer";
env.ADMIN_PASSWORD = adminPassword;
env.BETTER_AUTH_SECRET = authSecret;
env.NODE_ENV = env.NODE_ENV || "development";
env.VITE_API_BASE = env.VITE_API_BASE || "/api";

devVars.DATABASE_URL = databaseUrl;
devVars.OWNER_ID = ownerId;
devVars.APP_URL = env.APP_URL === "http://localhost:5173" ? "http://localhost:8787" : env.APP_URL;
devVars.BETTER_AUTH_SECRET = authSecret;
devVars.ADMIN_EMAIL = env.ADMIN_EMAIL;
devVars.ADMIN_PASSWORD = adminPassword;
if (env.RESEND_API_KEY) {
  devVars.RESEND_API_KEY = env.RESEND_API_KEY;
} else if (devVars.RESEND_API_KEY) {
  env.RESEND_API_KEY = devVars.RESEND_API_KEY;
}

writeFileSync(
  envPath,
  stringifyEnv(env, ["# Generated/updated by npm run setup — do not commit", ""]),
);
writeFileSync(
  devVarsPath,
  stringifyEnv(devVars, ["# Wrangler local secrets — do not commit", ""]),
);
log("sync .env ↔ apps/web/.dev.vars");

writeFileSync(
  join(root, "apps/web/.env"),
  stringifyEnv({ VITE_API_BASE: env.VITE_API_BASE }, [
    "# Generated by npm run setup — do not commit",
    "",
  ]),
);
log("write apps/web/.env");

const sync = spawnSync(process.execPath, [join(root, "scripts/rules-sync.mjs")], {
  cwd: root,
  stdio: "inherit",
});
if (sync.status !== 0) {
  console.error("\nrules:sync failed");
  process.exit(sync.status ?? 1);
}

const needsDb = isPlaceholderDb(databaseUrl);
console.log("\nDone.\n");
console.log("Next:");
if (needsDb) {
  console.log("  1. Set DATABASE_URL in .env (Neon connection string)");
  console.log("  2. Re-run: npm run setup");
  console.log("  3. npm install");
  console.log("  4. npm run db:migrate && npm run db:seed");
  console.log("  5. npm run dev");
} else {
  console.log("  npm install");
  console.log("  npm run db:migrate && npm run db:seed");
  console.log("  npm run dev");
}
console.log("");
